### ISSUE TITLE
fluentd dependency in nexus-iq-server-ha ignores custom image registry

### ISSUE THREAD

**Issue by bavugisainath** [sonatype/nexus-iq-server-ha#57]
I'm using the `nexus-iq-server-ha` Helm chart and attempting to customize the `fluentd` image using a public ECR repository. While the main container for the `nexus-iq-server-ha` deployment pulls the correct image, the `fluentd` StatefulSet (created via the dependency chart) does not correctly respect the custom registry setting.

Here is a snippet from my `values.yaml`:

```
fluentd:
  enabled: true
  image:
    repository: "public.ecr.aws/bitnami/fluentd"
``` 

fluentd container from Nexus IQ deployment fetches correct image value:
```
public.ecr.aws/bitnami/fluentd:<tag>

``` 

fluentd pod from fluentd statefulset fetches incorrect image value:
```
docker.io/public.ecr.aws/bitnami/fluentd:<tag>

``` 

It appears that the chart is prepending docker.io by default, even when a fully qualified repository is provided.

## Request
Please update the Helm chart to allow overriding the image.registry value explicitly, or correctly parse the image.repository to prevent the docker.io prefix when a custom registry is in use.

Example desired configuration:
```
fluentd:
  enabled: true
  image:
    registry: "public.ecr.aws"
    repository: "bitnami/fluentd"
    tag: "1.18.0-debian-12-r18"
```
